### ISSUE TITLE
EJB-Specific extensions how should/can I/we proceed

### ISSUE THREAD

**Issue by aschoerk** [cdi-unit/cdi-unit#109]
Hello,
at out company we implement unit-tests with cdi-unit for about 3 years. The idea is to do complete blackbox module- or artifact-tests. Meanwhile a specific maven-module has been created which contains extensions we had to implement for each of the projects. 
These extension I put into a github-module [ejb-cdi-unit](https://github.com/1and1/ejb-cdi-unit). 
Now I am looking for a reasonable way either to integrate these changes with cdi-unit, or to make cdi-unit better adaptable so that some code-copying I did, is not necessary anymore. 
I started this issue to come to ideas, how to go forward. 
A speciality at out site is, that we yet need to support weld 1.1.14 since most of our deployable yet run on jboss7.

**Comment by seanf** [comment]
Hi @aschoerk 

Hmm. That could be tricky, because I recently merged https://github.com/BrynCooke/cdi-unit/pull/105 into `master`, which removed all support for Weld 1.x for the upcoming [CDI-Unit 4.0](https://github.com/BrynCooke/cdi-unit/issues/108).

In terms of making CDI-Unit more adaptable, what did you have in mind?

**Comment by aschoerk** [comment]
Hello @seanf 

thanks for the answer..... I would rather switch today than tomorrow but this "RMI-Version-Lockin" of jboss makes it almost impossible.

concerning the adaptability:
I copied EjbRunner and WeldTestUrlDeployment only because I had to add classesToProcess.add(SupportEjbExtended.class) 
Everything else could be handled using the Annotations of SupportEjbExtended. 
So if there was an easy way to do this in a special Runner it would be nice. I admit this is not much but I want to avoid that people forget necessary annotations and initialisations which automatically come with @SupportEjbExtended.

**Comment by sventorben** [comment]
@seanf
I removed support for Weld 1.x in 43ce81f65d5ac5490a3e0aef122541d3bf23e466 mainly because the tests failed (see https://travis-ci.org/BrynCooke/cdi-unit/builds/210230383) and I thought getting rid of some "legacy" would be nice.
If we get the tests fixed, support for Weld 1.x should not be much of an issue, I guess.

**Comment by aschoerk** [comment]
Hallo, 
1. @sventorben  I reintroduced a solution for the 1.x incompatibility. I hope travis is also ok with that. Perhaps this could be used?

1. @seanf  Adaptability of CdiRunner -- perhaps WeldTestUrlDeployment could ask for: "more classes to process", more alternatives, to...  by a kind of AdaptionDelegate which can be registered.

1. Question: CdiRunner used for EjbTest: I would like to know, how often this is done and whether it was reasonable to add some functionality from ejb-cdi-unit in cdi-unit itself. I used EjbExtension as suggestion,  but it went not far enough for our test-situations.

**Comment by aschoerk** [comment]
@sventorben : ok, the simple solution by reintroducing your code did not work. I will have to look into this a bit deeper.

**Comment by seanf** [comment]
On 6 July 2017 at 20:47, Andreas Schörk <notifications@github.com> wrote:

> Hallo,
>
>    1.
>
>    @sventorben <https://github.com/sventorben> I reintroduced a solution
>    for the 1.x incompatibility. I hope travis is also ok with that. Perhaps
>    this could be used?
>    2.
>
>    @seanf <https://github.com/seanf> Adaptability of CdiRunner -- perhaps
>    WeldTestUrlDeployment could ask for: "more classes to process", more
>    alternatives, to... by a kind of AdaptionDelegate which can be registered.
>
>
I have a custom CdiRunner (subclass) which needs a special CDI extension,
and it would be nice to automatically add that extension class to the
deployment.

But instead of registering an AdaptionDelegate or similar, perhaps it would
be simpler to change the constructor of
WeldTestUrlDeployment/Weld11TestUrlDeployment so that it accepts a list of
extra classes, plus an overridable method in [Ng]CdiRunner like this?

// Perhaps this should be declared in a common interface, to enable
// more code sharing between CdiRunner and NgCdiRunner in future.
protected List<Class<?>> getAdditionalClasses() {
    return emptyList();
}

Then the Weld.createDeployment methods in [Ng]CdiRunner would just
getAdditionalClasses() and pass them to the
WeldTestUrlDeployment/Weld11TestUrlDeployment constructor.


> 3. Question: CdiRunner used for EjbTest: I would like to know, how often
> this is done and whether it was reasonable to add some functionality from
> ejb-cdi-unit in cdi-unit itself. I used EjbExtension as suggestion, but it
> went not far enough for our test-situations.


I'm not using EJBs in my projects, but I don't see a problem with adding
EjbRunner to CDI-Unit. It might be best to keep it in a separate jar, so
that users won't need extra EJB dependencies (if any) to use vanilla
CDI-Unit.

On the other hand, do you think EjbRunner is likely to break compatibility
for existing tests if its extra functionality were merged into the existing
EjbExtension and triggered by @SupportEjb? (I suppose minor breakage would
be okay if this gets in for CDI-Unit 4.0.)

**Comment by aschoerk** [comment]
@sventorben  

ahhh, now I see the similarity of NgCdiRunner, I have not been aware of this. I can prepare a proposal, plus additional Runner

I fear, anybody using @SupportEjb might, at first, not be happy with my changes since:
* each @Resource will become @Inject and therefore any Simulator will have to be available, except those which already a re available like SessionContext, MessageContext, ..., Queue, Topic, ConnectionFactory,  
* the Transactionhandling differs substantially.

**Comment by aschoerk** [comment]
@sventorben 
A [proposal](https://github.com/aschoerk/cdi-unit/commit/5592287fa31549cb380dbf66ec3a0287c24b0be1)
by overloading getTestConfiguration the proposed changes can be introduce by simple subclassing.

**Comment by seanf** [comment]
Okay, perhaps we should make the ejb-cdi-unit enhancements optional then,
and keep SupportEjb as is.

What if we add these annotations:

   - SupportEjbResource
   - SupportEjbTransactions
   - or a single one: SupportEjbExtra??

So they can be added to tests which use the existing runners, along with an
EjbCdiRunner which simply enables these features by default.

BTW I assume you've seen https://github.com/BrynCooke/cdi-unit/issues/90 ?
I imagine it's a tiny subset of ejb-cdi-unit, but it hints at how other
other people are using EJBs with CDI-Unit.

**Comment by sventorben** [comment]
@aschoerk Sorry for the late reply.
The link to your proposal does not seem to work. Can you check that please and re-post a link?

**Comment by aschoerk** [comment]
@sventorben thank you for your response. The proposal meanwhile has been included by @seanf

**Comment by aschoerk** [comment]
@seanf 
concerning extra module verses including into cdi-unit: I think at the moment there seems not to be a very strong movement in the direction of EJB-Testing and it's problems. So therefore I think I like to stay with the extramodule. 
Would it  be possible to mention it as such in the code of EjbExtension and the README.md

**Comment by seanf** [comment]
@sventorben the proposal was part of https://github.com/BrynCooke/cdi-unit/pull/110 but it morphed into https://github.com/BrynCooke/cdi-unit/pull/111 (with the new TestConfiguration class).

**Comment by seanf** [comment]
@aschoerk That sounds reasonable to me. Could you put in a PR with your suggested changes, please?

**Comment by seanf** [comment]
@aschoerk @sventorben @BrynCooke You might be interested in #115. 

If this multi-Weld compatibility problem (and the reflection tricks) get much worse, it might be necessary to add extra modules which abstract the differences between different Weld versions. I tried changing the main cdi-unit code to compile against Weld 3.0 instead of Weld 2.4, but it caused more problems than I wanted to solve right now.

**Comment by ikysil** [comment]
It looks like [ioc-unit](https://github.com/1and1/ioc-unit) is much better suited for the task.
